title: Snowpirate
description: your document description
theme: just-the-docs
#theme: jekyll-theme-minimal
#logo: "your_logo_path"
#favicon_ico: "your_icon_path"

url: snowpirate.github.io

aux_links:
  Repository: snowpirate.github.io
